#!/bin/bash
# linux-ck-autobuild-daemon.sh
VERSION=0.4.0
# Author: Jochum D, jooch (at) gmx (dot) com
# License: GPL3
# About: This script is part of linux-ck-autobuild, checks for new versions and automatically
#        starts the build script.
# Usage: Setup configuration parameters and run 'linux-ck-autobuild --enable-daemon' to enable.

program_name="linux-ck-autobuild"
window_title="Linux-ck autobuild"

function dialog {
	(
		increasefactor=$(echo "${TIMEOUT}"/100|bc -l)
		counter=0
		while [ "$counter" -le 100 ]; do
			echo $counter; sleep "${increasefactor}""${TIMEOUT_UNIT}"
			counter=$(( $counter + 1 ))
		done
	) |
	if zenity --text="New kernel version detected ($latest_version), build wil start in $TIMEOUT$TIMEOUT_UNIT" --title="$window_title" --progress --percentage=0 --auto-close; then
		echo "Waiting for sufficient system resources"
		load_avg=$(cat /proc/loadavg | cut -c 11-14)
		while true; do
		[[ "$load_avg" < "0.20" ]] && break
		sleep 30s
		done
		linux-ck-autobuild
	else
		zenity --info --width=350 --title="$window_title" --text="Update postponed for $POSTPONED"
		sleep $POSTPONED
	fi
	return
}

if [ -r /home/$USER/.config/$program_name/$program_name.conf ]; then
	. /home/$USER/.config/$program_name/$program_name.conf
	check_service="$(systemctl is-active linux-ck-autobuild@$USER.service)"
	while true
	do
		latest_version=$(curl -s https://aur.archlinux.org/packages/linux-ck | grep -o -P '(?<=linux-ck ).*(?=</h2)')
		last_build=$(cat $BUILDDIR/linux-ck/.last_build)

		echo "Checking latest kernel version"
		if [[ $latest_version == $last_build ]]; then
			echo "Kernel is up to date"
			sleep $WATCHDOG_INTERVAL
		else
			if [[ $service_state = "active" ]] || [ -r /etc/systemd/system/multi-user.target.wants/linux-ck-autobuild@$USER.service ]; then
			
			option=("Disable systemd service" "Disable autostart" "Quit")
			answer=$(zenity  --list --width=350 --title="$window_title" --text="<b>ERROR</b>: systemd service is enabled or active." --hide-header --column=Option "${option[@]}")
			case "$answer" in 
				"${option[0]}") 
				gksu systemctl disable linux-ck-autobuild@$USER.service
				;; 
				"${option[1]}") 
				rm /home/$USER/.config/autostart/$program_name-daemon.desktop && exit 1
				;; 
				"${option[2]}") 
				exit 1
				;; 
			esac

			else
			dialog
			fi
		fi
	done
else
	echo "ERROR: no configuration found, run '$program_name -c'"
	exit
fi	
